apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ypgl84xck-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ypgl84xck-go 
  name: ypgl84xck-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ypgl84xck-go 
